import numpy as np

plots = {
  # "SM": {
  #   "title": r"Variance contributions to $a_{\mu}^{\text{SM}}$",
  #   "outfile": "chapters/01-introduction/img/a_mu_sm_variances_squares.pdf",
  #   "figsize": (12, 10),
  #   "data": {
  #     "LO-HVP": {
  #       "label": "LO-HVP",
  #       "error": 61.0,
  #       "position": (0,0),
  #       "padding": (5,0),
  #     },
  #     "Hlbl": {
  #       "label": "Hlbl",
  #       "error": 9.9,
  #       "position": lambda a: (a.dX[-2]+5, a.h-a.dY[-1]),
  #       "padding": (5,0),
  #     },
  #     "EW": {
  #       "label": "EW",
  #       "error": 4.0,
  #       "text_offset": (8,0),
  #       "position": lambda a: (a.dX[-3]+5, a.h-a.dY[-2]-a.dY[-1]-5),
  #       "padding": (5,0),
  #     },
  #     "QED": {
  #       "label": "QED",
  #       "error": 2.0,
  #       "text_offset": (8,0),
  #       "position": lambda a: (a.dX[-4]+5, a.h-a.dY[-3]-a.dY[-2]-a.dY[-1]-2*5),
  #       "padding": (10,0),
  #     },
  #     "N(N)LO-HVP": {
  #       "label": "N(N)LO-HVP",
  #       "error": np.sqrt(1.3**2 + 1**2),
  #       "position": lambda a: (a.dX[-5]+5, a.h-a.dY[-4]-a.dY[-3]-a.dY[-2]-a.dY[-1]-3*5),
  #       "text_offset": (10,0),
  #       "padding": (5,0),
  #     },
  #   },
  # },
  "SM": {
    "title": r"Variance contributions to $a_{\mu}^{\text{SM}}$",
    "outfile": "chapters/01-introduction/img/a_mu_sm_variances_squares.pdf",
    "figsize": (7, 5),
    "data": {
      "LO-HVP": {
        "label": "LO-HVP",
        "error": 61.0,
        "position": (0,0),
        "padding": (5,0),
      },
      "Hlbl": {
        "label": "Hlbl",
        "error": 9.9,
        "position": lambda a: (a.dX[-2]+7, a.h-a.dY[-1]),
        "text_offset": (0,-7),
        "padding": (5,0),
      },
      "EW": {
        "label": "EW",
        "error": 4.0,
        "position": lambda a: (a.X[-1]+a.dX[-2]/2-a.dX[-1]/2, a.h-a.dY[-2]-a.dY[-1]-9),
        "text_offset": (0,-5),
        "padding": (5,0),
      },
      "QED": {
        "label": "QED",
        "error": 2.0,
        "position": lambda a: (a.X[-1]+a.dX[-2]/2-a.dX[-1]/2, a.h-a.dY[-3]-a.dY[-2]-a.dY[-1]-9-10),
        "text_offset": (0,-4),
        "padding": (10,0),
      },
      "N(N)LO-HVP": {
        "label": "N(N)LO-HVP",
        "error": np.sqrt(1.3**2 + 1**2),
        "position": lambda a: (a.X[-1]+a.dX[-2]/2-a.dX[-1]/2, a.h-a.dY[-4]-a.dY[-3]-a.dY[-2]-a.dY[-1]-9-10-10),
        "text_offset": (0,-4),
        "padding": (5,0),
      },
    },
  },
  "LO-HVP": {
    "title": r"Variance contributions to $a_{\mu}^{\text{LO-HVP}}$",
    "figsize": (8,5),
    "outfile": "chapters/01-introduction/img/a_mu_lohvp_variances_squares.pdf",
    "data": {
      "ud": {
        "label": "light (up, down)",
        "error": 500,
        "position": (0,0),
        "padding": (5,0),
      },
      "disc": {
        "label": "disconnected",
        "error": 230,
        "position": lambda a: (a.dX[-2]+5, a.h-a.dY[-1]),
        "padding": (5,0),
      },
      "s": {
        "label": "strange",
        "error": 28,
        "position": lambda a: (a.X[-1]+a.dX[-2]/2-a.dX[-1]/2, a.h-a.dY[-2]-a.dY[-1]-6),
        "text_offset": (0,-5),
        "padding": (5,0),
      },
      "c": {
        "label": "charm",
        "error": 11,
        "position": lambda a: (a.X[-1]+a.dX[-2]/2-a.dX[-1]/2, a.h-a.dY[-3]-a.dY[-2]-a.dY[-1]-6-10),
        "text_offset": (0,-4),
        "padding": (5,0),
      },
    },
  },
  "Windows": {
    "title": r"Variance of window contributions to $a_{\mu}^{\text{SM}}$",
    "figsize": (9,5),
    "outfile": "chapters/01-introduction/img/a_mu_windows_variances_squares.pdf",
    "data": {
      "LD": {
        "label": "LD",
        "error": 50,
        "position": (0,0),
        "padding": (5,0),
      },
      "IB": {
        "label": "IB",
        "error": 34,
        "position": lambda a: (a.dX[-2]+5, a.h-a.dY[-1]),
        "padding": (5,0),
      },
      "W": {
        "label": "W",
        "error": 4.2,
        "position": lambda a: (a.dX[-3]+10, a.h-a.dY[-2]-a.dY[-1]-5),
        "text_offset": (0,-5),
        "padding": (5,0),
      },
      "SD": {
        "label": "SD",
        "error": 2.2,
        "position": lambda a: (a.dX[-4]+30, a.h-a.dY[-3]-a.dY[-2]-5),
        "text_offset": (0,-4),
        "padding": (5,0),
      },
    },
  },
  # "LO-HVP": {
  #   "title": r"Variance contributions to $a_{\mu}^{\text{LO-HVP}}$",
  #   "figsize": (15,10),
  #   "outfile": "chapters/01-introduction/img/a_mu_lohvp_variances_squares.pdf",
  #   "data": {
  #     "ud": {
  #       "label": "light (up, down)",
  #       "error": 500,
  #       "position": (0,0),
  #       "padding": (5,0),
  #     },
  #     "disc": {
  #       "label": "disconnected",
  #       "error": 230,
  #       "position": lambda a: (a.dX[-2]+5, a.h-a.dY[-1]),
  #       "padding": (5,0),
  #     },
  #     "s": {
  #       "label": "strange",
  #       "error": 28,
  #       "position": lambda a: (a.dX[-3]+5, a.h-a.dY[-2]-a.dY[-1]-5),
  #       "text_offset": (8,0),
  #       "padding": (5,0),
  #     },
  #     "c": {
  #       "label": "charm",
  #       "error": 11,
  #       "position": lambda a: (a.dX[-4]+5, a.h-a.dY[-3]-a.dY[-2]-a.dY[-1]-2*5),
  #       "text_offset": (8,0),
  #       "padding": (5,0),
  #     },
  #   },
  # },
  # "Windows": {
  #   "title": r"Variance of window contributions to $a_{\mu}^{\text{SM}}$",
  #   "figsize": (17.5,10),
  #   "outfile": "chapters/01-introduction/img/a_mu_windows_variances_squares.pdf",
  #   "data": {
  #     "LD": {
  #       "label": "LD",
  #       "error": 50,
  #       "position": (0,0),
  #       "padding": (5,0),
  #     },
  #     "IB": {
  #       "label": "IB",
  #       "error": 34,
  #       "position": lambda a: (a.dX[-2]+5, a.h-a.dY[-1]),
  #       "padding": (5,0),
  #     },
  #     "W": {
  #       "label": "W",
  #       "error": 4.2,
  #       "position": lambda a: (a.dX[-3]+5, a.h-a.dY[-2]-a.dY[-1]-5),
  #       "text_offset": (10,0),
  #       "padding": (5,0),
  #     },
  #     "SD": {
  #       "label": "SD",
  #       "error": 2.2,
  #       "position": lambda a: (a.dX[-4]+5, a.h-a.dY[-3]-a.dY[-2]-a.dY[-1]-2*5),
  #       "text_offset": (12,0),
  #       "padding": (5,0),
  #     },
  #   },
  # },
  # "SM-value": {
  #   "title": r"Value contributions to $a_{\mu}^{\text{SM}}$",
  #   "outfile": "chapters/01-introduction/img/a_mu_sm_values_squares.pdf",
  #   "figsize": (12, 10),
  #   "data": {
  #     "QED": {
  #       "label": "QED",
  #       "error": np.sqrt(116584718.8),
  #       "position": (0,0),
  #       "padding": (10,0),
  #     },
  #     "LO-HVP": {
  #       "label": "LO-HVP",
  #       "error": np.sqrt(7132.0),
  #       "position": lambda a: (a.dX[-2]+5, a.h-a.dY[-1]),
  #       "text_offset": (10,0),
  #       "padding": (5,0),
  #     },
  #     "EW": {
  #       "label": "EW",
  #       "error": np.sqrt(154.4),
  #       "position": lambda a: (a.dX[-3]+5, a.h-a.dY[-2]-a.dY[-1]-5),
  #       "text_offset": (10,0),
  #       "padding": (5,0),
  #     },
  #     "Hlbl": {
  #       "label": "Hlbl",
  #       "error": np.sqrt(115.5),
  #       "position": lambda a: (a.dX[-4]+5, a.h-a.dY[-3]-a.dY[-2]-a.dY[-1]-2*5),
  #       "text_offset": (10,0),
  #       "padding": (5,0),
  #     },
  #     "N(N)LO-HVP": {
  #       "label": "N(N)LO-HVP",
  #       "error": np.sqrt(87.2),
  #       "position": lambda a: (a.dX[-5]+5, a.h-a.dY[-4]-a.dY[-3]-a.dY[-2]-a.dY[-1]-3*5),
  #       "text_offset": (10,0),
  #       "padding": (5,0),
  #     },
  #   },
  # },
}
